// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SLR Automation": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/wimspaargaren/slr-automation/src/slr-api/design
// --out=$(GOPATH)/src/github.com/wimspaargaren/slr-automation/src/slr-api
// --version=v1.4.1

package app

import (
	"fmt"
	"strings"
)

// ProjectHref returns the resource href.
func ProjectHref(projectID interface{}) string {
	paramprojectID := strings.TrimLeftFunc(fmt.Sprintf("%v", projectID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/project/%v", paramprojectID)
}
