// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "SLR Automation": Application User Types
//
// Command:
// $ goagen
// --design=github.com/wimspaargaren/slr-automation/src/slr-api/design
// --out=$(GOPATH)/src/github.com/wimspaargaren/slr-automation/src/slr-api
// --version=v1.4.1

package app
